spring.application.name=jobhub

spring.datasource.url=jdbc:mysql://localhost:3306/jobhub_db
spring.datasource.username=root
spring.datasource.password=Aaradhy@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

jwt.secret=4x7R9kLmP2qWs8Vn5YtBc3DfGhJkLpQzXcMvBnAsDeFgHiJkLmNoPqRsTuVwXyZ12
jwt.expiration=86400000 
#  24 Hours After 24 hours, the token becomes invalid.

#CONFIGURATIONS TO UPLOAD THE CERTIFICATE/RESUME
spring.servlet.multipart.enabled=true
#enables file upload
spring.servlet.multipart.max-file-size=5MB
#Rejects files larger than 5 MB.
spring.servlet.multipart.max-request-size=5MB
#max-request-size=5MB ? Limits the total request size.